In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
df = pd.read_csv("cardio_train_new.csv")

In [ ]:
import seaborn as sns
corr = df.corr()
fig, ax = plt.subplots(figsize=(15,10))
sns.heatmap(corr,
        xticklabels=corr.columns,
        yticklabels=corr.columns,
            annot=True, );

In [ ]:
df["BMI"] = round(df.weight/(df.height/100)**2, 2)
df.age = round(df.age/365,1)
df = df.drop("id", axis=1)
df

age  gender  height  weight  ap_hi  ap_lo  cholesterol  gluc  smoke  \
0      50.4       2     168    62.0    110     80            1     1      0   
1      55.4       1     156    85.0    140     90            3     1      0   
2      51.7       1     165    64.0    130     70            3     1      0   
3      48.3       2     169    82.0    150    100            1     1      0   
4      47.9       1     156    56.0    100     60            1     1      0   
...     ...     ...     ...     ...    ...    ...          ...   ...    ...   
69995  52.7       2     168    76.0    120     80            1     1      1   
69996  61.9       1     158   126.0    140     90            2     2      0   
69997  52.2       2     183   105.0    180     90            3     1      0   
69998  61.5       1     163    72.0    135     80            1     2      0   
69999  56.3       1     170    72.0    120     80            2     1      0   

       alco  active    BMI  cardio  
0         0       1  21.97       0  
1         0       1  34.93       1  
2         0       0  23.51       1  
3         0       1  28.71       1  
4         0       0  23.01       0  
...     ...     ...    ...     ...  
69995     0       1  26.93       0  
69996     0       1  50.47       1  
69997     1       0  31.35       1  
69998     0       0  27.10       1  
69999     0       1  24.91       0  

[70000 rows x 13 columns]

In [ ]:
x = df.drop("cardio", axis=1)
y = df.cardio

In [ ]:
x.shape, y.shape

((70000, 12), (70000,))

In [ ]:
y

0        0
1        1
2        1
3        1
4        0
        ..
69995    0
69996    1
69997    1
69998    1
69999    0
Name: cardio, Length: 70000, dtype: int64

In [ ]:
def make_model(model,x,y):

  clf = model(n_jobs=1)
  clf.fit(x, y)
  return clf

In [ ]:
def accuracy(model,x,y):
  r2 = round(r2_score(x,y), 2)
  acuury = round(accuracy_score(x,y)*100, 2)
  f1 = round(f1_score(x,y), 2)
  print("the accuracy score of " + model + " is:")
  print(str(acuury)+"%")
  print("the f1 score of " + model + " is:")
  print(str(f1))
  print("the r2 score of " + model + " is:")
  print(str(r2))
  print("the Confusion Matrix Display of " + model + " is:")
  print(confusion_matrix(x,y))


In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split,GridSearchCV
from xgboost import XGBClassifier
from sklearn.metrics import confusion_matrix, f1_score, accuracy_score, r2_score, classification_report
from sklearn.metrics import ConfusionMatrixDisplay
from sklearn.neighbors import KNeighborsClassifier

np.random.seed(42)
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

XGB_clf = make_model(XGBClassifier,x_train,y_train)
RF_clf = make_model(RandomForestClassifier,x_train,y_train)
KN_clf = make_model(KNeighborsClassifier,x_train,y_train)


XGB_pre = XGB_clf.predict(x_test)
RF_pre = RF_clf.predict(x_test)
KN_pre = KN_clf.predict(x_test)

In [ ]:
accuracy("XGB",XGB_pre,y_test)

the accuracy score of XGB is:
73.81%
the f1 score of XGB is:
0.73
the r2 score of XGB is:
-0.05
the Confusion Matrix Display of XGB is:
[[5425 2104]
 [1563 4908]]


In [ ]:
accuracy("RF",RF_pre,y_test)

the accuracy score of RF is:
71.16%
the f1 score of RF is:
0.71
the r2 score of RF is:
-0.15
the Confusion Matrix Display of RF is:
[[5019 2069]
 [1969 4943]]


In [ ]:
accuracy("KN",KN_pre,y_test)

the accuracy score of KN is:
68.56%
the f1 score of KN is:
0.68
the r2 score of KN is:
-0.26
the Confusion Matrix Display of KN is:
[[4945 2358]
 [2043 4654]]


In [ ]:
grid_2 = {'n_estimators': [100, 200, 500],
          'max_depth': [None],
          'max_features': ['auto', 'sqrt'],
          'min_samples_split': [6],
          'min_samples_leaf': [1, 2]}

In [330]:
# Setup GridSearchCV
gs_clf = GridSearchCV(estimator=RF_clf,
                      param_grid=grid_2,
                      cv=5,
                      verbose=2)

#Fit the GridSearchCV version of clf
gs_clf.fit(x_train, y_train);

Fitting 5 folds for each of 12 candidates, totalling 60 fits
[CV] END max_depth=None, max_features=auto, min_samples_leaf=1, min_samples_split=6, n_estimators=100; total time=   8.6s
[CV] END max_depth=None, max_features=auto, min_samples_leaf=1, min_samples_split=6, n_estimators=100; total time=   6.6s
[CV] END max_depth=None, max_features=auto, min_samples_leaf=1, min_samples_split=6, n_estimators=100; total time=  10.2s
[CV] END max_depth=None, max_features=auto, min_samples_leaf=1, min_samples_split=6, n_estimators=100; total time=   7.2s
[CV] END max_depth=None, max_features=auto, min_samples_leaf=1, min_samples_split=6, n_estimators=100; total time=   8.0s
[CV] END max_depth=None, max_features=auto, min_samples_leaf=1, min_samples_split=6, n_estimators=200; total time=  14.8s
[CV] END max_depth=None, max_features=auto, min_samples_leaf=1, min_samples_split=6, n_estimators=200; total time=  14.7s
[CV] END max_depth=None, max_features=auto, min_samples_leaf=1, min_samples_split=6, 

In [ ]:
gs_clf.best_params_

In [ ]:
#accuracy("GS",gs_clf.predict(x_test),y_test)

In [ ]:
from xgboost import plot_importance
feature_importance_scores = XGB_clf.feature_importances_
feature_importance_scores

array([0.05571519, 0.0208953 , 0.02069444, 0.02539466, 0.5175227 ,
       0.02787975, 0.16248938, 0.03442602, 0.03939352, 0.03731234,
       0.03473605, 0.02354063], dtype=float32)

In [310]:
predicted_probabilities = XGB_clf.predict_proba(x_test)
predicted_probabilities = predicted_probabilities*100
predicted_probabilities

array([[17.899454, 82.10055 ],
       [15.869808, 84.13019 ],
       [35.03631 , 64.96369 ],
       ...,
       [46.782146, 53.217854],
       [21.722496, 78.277504],
       [17.196352, 82.80365 ]], dtype=float32)

In [328]:
probability_df = pd.DataFrame(predicted_probabilities, columns=['Probability_Class_0', 'Probability_Class_1'])
probability_df.isna().sum()
round(probability_df, 2)
probability_df

Probability_Class_0  Probability_Class_1
0                17.899454            82.100548
1                15.869808            84.130188
2                35.036308            64.963692
3                63.358444            36.641556
4                77.378044            22.621956
...                    ...                  ...
13995            54.347809            45.652191
13996            69.311157            30.688841
13997            46.782146            53.217854
13998            21.722496            78.277504
13999            17.196352            82.803650

[14000 rows x 2 columns]

In [320]:
confusion_matrix(y_test, RF_pre)


array([[5019, 1969],
       [2069, 4943]])

In [321]:
y_test2 = pd.DataFrame(y_test)
y_test2.reset_index(inplace=True)
y_test2

index  cardio
0      46730       1
1      48393       1
2      41416       1
3      34506       1
4      43725       0
...      ...     ...
13995  21525       1
13996  16276       1
13997  24390       0
13998  28061       1
13999  63452       1

[14000 rows x 2 columns]

In [322]:
test_data_with_probabilities=pd.concat([y_test2, probability_df], axis=1)
test_data_with_probabilities.drop("index", axis=1, inplace=True)
test_data_with_probabilities

cardio  Probability_Class_0  Probability_Class_1
0           1            17.900000            82.099998
1           1            15.870000            84.129997
2           1            35.040001            64.959999
3           1            63.360001            36.639999
4           0            77.379997            22.620001
...       ...                  ...                  ...
13995       1            54.349998            45.650002
13996       1            69.309998            30.690001
13997       0            46.779999            53.220001
13998       1            21.719999            78.279999
13999       1            17.200001            82.800003

[14000 rows x 3 columns]